version: '3.7'
services:
  jam:
    restart: always
    image: ffalt/jam:latest
    container_name: jam
    volumes:
      - type: bind
        source: ./data/config
        target: /home/app/jam/config
      - type: bind
        source: ./data/data
        target: /home/app/jam/data
      - type: bind
        source: ./data/logs
        target: /home/app/jam/logs
      - type: bind
        source: ./data/media
        target: /usr/share/media
    user: app
    command: sh /home/app/start.sh
    ports:
      - "0.0.0.0:4040:4040"

