version: '3.7'
services:
  elastic:
    restart: always
    container_name: elasticsearch-jam
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
    environment:
      - "cluster.name=elasticsearch"
      - "node.name=Jam Fever"
      - "network.host=0.0.0.0"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - type: bind
        source: ./data/db/elastic
        target: /usr/share/elasticsearch/data/
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
  jam:
    restart: always
    image: ffalt/jam:latest
    container_name: jam
    volumes:
      - type: bind
        source: ./data/config
        target: /home/app/jam/config
      - type: bind
        source: ./data/data
        target: /home/app/jam/data
      - type: bind
        source: ./data/logs
        target: /home/app/jam/logs
      - type: bind
        source: ./data/media
        target: /usr/share/media
    user: app
    command: sh /home/app/start.sh
    environment:
      DATABASE_CHECK: http://elasticsearch:9200/_cluster/health
    depends_on:
      - elastic
    links:
      - elastic:elastic
    ports:
      - "0.0.0.0:4040:4040"

